-- Create a function to create the message_summaries table if it doesn't exist
CREATE OR REPLACE FUNCTION create_message_summaries_table()
RETURNS boolean
LANGUAGE plpgsql
AS $$
DECLARE
  table_exists boolean;
BEGIN
  -- Check if the table already exists
  SELECT EXISTS (
    SELECT FROM information_schema.tables 
    WHERE table_schema = 'public'
    AND table_name = 'message_summaries'
  ) INTO table_exists;
  
  -- If the table doesn't exist, create it
  IF NOT table_exists THEN
    CREATE TABLE message_summaries (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      message_id TEXT NOT NULL UNIQUE,
      summary TEXT NOT NULL,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL
    );
    
    -- Add index on message_id for faster lookups
    CREATE INDEX message_summaries_message_id_idx ON message_summaries (message_id);
    
    RETURN true;
  END IF;
  
  -- Table already exists
  RETURN false;
END;
$$; 