create table prompt_submissions (
  id bigint generated by default as identity primary key,
  wallet_address text not null,
  message text not null,
  short_description text not null,
  is_agent_a boolean not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
); 